version: "3.8"

volumes:
  app_data:

services:
  user-db:
    hostname: user-db
    image: library/mongo:latest
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - app_data:/data:db
    restart: always
    networks:
      - userdb

  job-db:
    hostname: job-db
    command: mongod --port 27019
    image: library/mongo:latest
    ports:
      - 27019:27019
    volumes:
      - app_data:/data:db
    restart: always
    networks:
      - jobdb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - app_data:/var/lib/rabbitmq
      - app_data:/etc/rabbitmq/rabbitmq.config
      - app_data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    networks:
      - rabbitmq

  frontend:
    # platform: linux/amd64
    build: ./job-board-client
    image: lundaljung/frontend:latest
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - api-gateway
      - user-service
      - job-service
      - notification-service
    networks:
      - frontend
    restart: always
    environment:
      - REACT_APP_API_BASE=http://ec2-16-16-216-183.eu-north-1.compute.amazonaws.com:8000

  api-gateway:
    # platform: linux/amd64
    build: ./microservices/api-gateway
    image: lundaljung/api-gateway:latest
    ports:
      - 8000:8000
    environment:
      - JOB_MANAGEMENTE_HOST=http://job-service
      - USER_MANAGEMENT_HOST=http://user-service
    networks:
      - frontend
      - backend
    restart: always

  notification-service:
    # platform: linux/amd64
    build: ./microservices/notification-management
    image: lundaljung/notification-service:latest
    ports:
      - 8003:8003
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    restart: always
    networks:
      - rabbitmq
      - backend

  job-service:
    # platform: linux/amd64
    build: ./microservices/job-management
    image: lundaljung/job-service:latest
    ports:
      - 8002:8002
    environment:
      - DB_HOST=mongodb://job-db:27019/job-management
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - job-db
    restart: always
    networks:
      - backend
      - rabbitmq
      - jobdb

  user-service:
    # platform: linux/amd64
    build: ./microservices/user-management
    image: lundaljung/user-service:latest
    ports:
      - 8001:8001
    environment:
      - DB_HOST=mongodb://user-db:27018/user-management
      - SEED_URL=http://job-service:8002
    depends_on:
      - user-db
      - job-service
    restart: always
    networks:
      - backend
      - userdb

networks:
  userdb:
  jobdb:
  rabbitmq:
  frontend:
  backend:
