@startuml View/Edit a user
title View/Edit a User
autonumber
actor User #Red
participant APIGateway
participant User_Service
participant User_Service_DB
User -> APIGateway: Get a user request(View) or Update a user request(Edit) 
APIGateway -> User_Service:Pass to User_Service, If token is valid
APIGateway --> User: Response Error, If token is not valid
User_Service -> User_Service_DB: Get a user or Update a user
User_Service_DB --> User_Service: Ok or Error
User_Service --> APIGateway: Ok or Error
APIGateway --> User: Response Ok or Error
@enduml